language: php
before_install:
  - wget https://get.symfony.com/cli/installer -O - | bash
  - sudo mv /home/travis/.symfony/bin/symfony /usr/local/bin/symfony
cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache/files
branches:
  only:
    - master
node_js:
  - '10'
php:
  - '7.4'
install:
  - composer install
script:
  - php bin/phpunit
  - symfony check:security
before_deploy:
  - rm -rf bin/.phpunit
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
