version: '3'
services:
  php:
    build: .docker/php
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
