service: sf4bref

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2
    apiKeys:
      - apiKey
    environment:
      APP_ENV: prod
      #Don't put sensitive values here!

plugins:
    - ./vendor/bref/bref

package:
  exclude:
    - ./**
  include:
    - bin/console
    - bin/phpunit
    - vendor/**
    - var/cache/prod/**
    - src/**
    - composer.json
    - composer.lock
    - symfony.lock
    - public/**
    - config/bootstrap.php
    - config/bundles.php
    - .env.local.php

functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http:
                path: /api/v1/notification/send
                method: post
                private: true
                request:
                  schema:
                    application/json: ${file(send_notification.json)}
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console layer"
